[tool.poetry]
name = "think-dsp"
version = "0.2.0"
description = "DSP utilities from the Think DSP book"
authors = ["Allen Downey <allen.downey@olin.edu>"]
maintainers = ["Kim Maxim <maksimkim005@gmail.com>"]
readme = "README.md"
license = "MIT"
packages = [{ include = "thinkdsp" }]
include = ["LICENSE"]
exclude = ["book", "code", ".devcontainer", ".github"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Education",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Multimedia :: Sound/Audio :: Analysis",
    "Topic :: Scientific/Engineering :: Mathematics",
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
numpy = ">=1.22.4,<3.0"
scipy = ">=1.13.0,<2.0"
matplotlib = ">=3.8.0,<4.0"
jupyter = { version = "^1.0.0", optional = true }
pandas = { version = "^1.1.4", optional = true }
seaborn = { version = "^0.11.0", optional = true }

[tool.poetry.extras]
notebooks = ["jupyter", "pandas", "seaborn"]

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[tool.black]
line-length = 88
target-version = ["py39"]
